//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace FileManager.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FileManagerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FileManagerEntities object using the connection string found in the 'FileManagerEntities' section of the application configuration file.
        /// </summary>
        public FileManagerEntities() : base("name=FileManagerEntities", "FileManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FileManagerEntities object.
        /// </summary>
        public FileManagerEntities(string connectionString) : base(connectionString, "FileManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FileManagerEntities object.
        /// </summary>
        public FileManagerEntities(EntityConnection connection) : base(connection, "FileManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FileManagerModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="user_Ref">Initial value of the User_Ref property.</param>
        /// <param name="user_Username">Initial value of the User_Username property.</param>
        /// <param name="user_Password">Initial value of the User_Password property.</param>
        /// <param name="user_Type">Initial value of the User_Type property.</param>
        public static User CreateUser(global::System.Int32 user_Ref, global::System.String user_Username, global::System.String user_Password, global::System.Int32 user_Type)
        {
            User user = new User();
            user.User_Ref = user_Ref;
            user.User_Username = user_Username;
            user.User_Password = user_Password;
            user.User_Type = user_Type;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 User_Ref
        {
            get
            {
                return _User_Ref;
            }
            set
            {
                if (_User_Ref != value)
                {
                    OnUser_RefChanging(value);
                    ReportPropertyChanging("User_Ref");
                    _User_Ref = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("User_Ref");
                    OnUser_RefChanged();
                }
            }
        }
        private global::System.Int32 _User_Ref;
        partial void OnUser_RefChanging(global::System.Int32 value);
        partial void OnUser_RefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User_Username
        {
            get
            {
                return _User_Username;
            }
            set
            {
                OnUser_UsernameChanging(value);
                ReportPropertyChanging("User_Username");
                _User_Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User_Username");
                OnUser_UsernameChanged();
            }
        }
        private global::System.String _User_Username;
        partial void OnUser_UsernameChanging(global::System.String value);
        partial void OnUser_UsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User_Password
        {
            get
            {
                return _User_Password;
            }
            set
            {
                OnUser_PasswordChanging(value);
                ReportPropertyChanging("User_Password");
                _User_Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User_Password");
                OnUser_PasswordChanged();
            }
        }
        private global::System.String _User_Password;
        partial void OnUser_PasswordChanging(global::System.String value);
        partial void OnUser_PasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 User_Type
        {
            get
            {
                return _User_Type;
            }
            set
            {
                OnUser_TypeChanging(value);
                ReportPropertyChanging("User_Type");
                _User_Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("User_Type");
                OnUser_TypeChanged();
            }
        }
        private global::System.Int32 _User_Type;
        partial void OnUser_TypeChanging(global::System.Int32 value);
        partial void OnUser_TypeChanged();

        #endregion

    
    }

    #endregion

    
}
